### ISSUE TITLE
Error colab

### ISSUE THREAD

**Issue by CesareDavidePace** [kadirnar/Yolov7-SAHI#1]
When I open the link for colab for the yolov7 guide, the message "notepad not found" appears.

**Comment by kadirnar** [comment]
Can you refresh the page and try again?

![image](https://user-images.githubusercontent.com/36204372/198247973-694c4b14-0277-45e8-ac5a-0708fbc8c055.png)

**Comment by CesareDavidePace** [comment]
now it works, thanks
