### ISSUE TITLE
Prediction with Yolov7 segmentation model

### ISSUE THREAD

**Issue by cmbean2** [kadirnar/Yolov7-SAHI#11]
Hi, I am looking for help with implementing SAHI with Yolov7 and specifically a segmentation model.

I have looked through the documentation I can find and tried different things, but nothing seems to work for me. When I follow your demo file everything runs correctly, but when I swap to my .pt file and my image then I get the following error message. 
The same issue comes up when I try the 'sliced_predictions' command as well.

I'd appreciate any help I can get to solve this issue. 
Thanks, Chris

![image](https://github.com/kadirnar/Yolov7-SAHI/assets/118309806/6b4aa8b4-e7ed-4ed8-bd7d-00f09c47a2c4)

**Comment by cmbean2** [comment]
@kadirnar wondering if you could help with this? It seems like you're the expert. Thanks for taking the time?

**Comment by kadirnar** [comment]
Hi, you should ask the [SAHI ](https://github.com/obss/sahi)repo. You should add segmentation properties to [this file](https://github.com/kadirnar/Yolov7-SAHI/blob/main/sahi/models/yolov7pip.py).

**Comment by kadirnar** [comment]
I am no longer developing this repo. I am developing different projects. I don't have time to develop this project :(

**Comment by cmbean2** [comment]
Okay, thanks! I appreciate even the quick message.

**Comment by kadirnar** [comment]
> Okay, thanks! I appreciate even the quick message.

https://github.com/obss/sahi/pull/882

**Comment by cmbean2** [comment]
I got this working. THANKS for directing me to the yolov8 implementation.
