### ISSUE TITLE
model already load,but the error is model is not loaded

### ISSUE THREAD

**Issue by C4712** [kadirnar/Yolov7-SAHI#2]
![image](https://user-images.githubusercontent.com/56387581/198952963-a551c4d2-7994-4560-9ede-7e35ce293887.png)

![image](https://user-images.githubusercontent.com/56387581/198953010-5a4be18d-cd23-4efb-a7c8-83ebfdc92bb4.png)

![image](https://user-images.githubusercontent.com/56387581/198953042-3fa5ba50-a9e2-4e66-9d04-f4c083081e08.png)

**Comment by kadirnar** [comment]
Hi @C4712 

Are you working locally? Are you using a custom model? Can you check the yolov7_model_path variable?

**Comment by IdrissSinapan974** [comment]
Hi ! 
I have same error, I work locally, I use a custom model  and my yolov7_model_path variable is correct (path to the weight I obtained after training). 
It worked the last time and now I don't know why It is not the case. 
Thank you :)

**Comment by kadirnar** [comment]
Can you share the error message?  Are you using the colab file?

**Comment by IdrissSinapan974** [comment]
![load2](https://user-images.githubusercontent.com/120011214/206524957-778c3794-c904-4d07-83ea-d0540ac8083b.PNG)
![load](https://user-images.githubusercontent.com/120011214/206523506-d7cadfe0-23ea-4540-b893-510a6f01fdfd.PNG)



I clone the repo in my computer, because I have to much data to import on colab...

**Comment by kadirnar** [comment]
Are you using the ipynb file? https://github.com/kadirnar/Yolov7-SAHI/blob/main/demo/inference_for_yolov7.ipynb

![image](https://user-images.githubusercontent.com/36204372/206528272-099a9b22-9bde-4e92-a8ac-f32fdcb85b9e.png)

**Comment by IdrissSinapan974** [comment]
![script](https://user-images.githubusercontent.com/120011214/207590214-95720454-db1c-44a9-9304-2703cdf8ad82.PNG)


Yes, I use the .ipynb file, I copy and past what I need and adapt the lines for my case. (yolov.pt is the weight I obtained after training )

**Comment by beratersari** [comment]
Same Issue

**Comment by IdrissSinapan974** [comment]
Resolved ! 
In model.py file, in "class Yolov7DetectionModel(DetectionModel):" they used torch.hub.load(...) and for this you need internet connection.... For my case, I tested the code, but after that I use it in a computer without internet connection. And this error appear. 
Hope it will help.

**Comment by beratersari** [comment]
I have an internet connection already. Do you use custom model? The original yolov7.pt works for me. But my custom model doesnt work

**Comment by IdrissSinapan974** [comment]
I did yolov7 training on my custom dataset, so I obtain best.pt. Then I used the obtain weight (best.pt renamed yolov7.pt) in SAHI. Do you have the exact same error (Model is not loaded ) ?

**Comment by kadirnar** [comment]
@IdrissSinapan974 

Does the error go away when I type the filename yolov7.pt?

**Comment by IdrissSinapan974** [comment]
@kadirnar no, the filename have no effect on this issue (for my case). I changed the filename to something different to "yolov7.pt"  and it works too.

**Comment by pythoncodeAshisH** [comment]
In model.py file, in "class Yolov7DetectionModel(DetectionModel):" they used torch.hub.load(...)


but In my case i have good internet connection still i got error

**Comment by IdrissSinapan974** [comment]
@pythoncodeAshisH, can you share the code section which gives you this error please ?

**Comment by pythoncodeAshisH** [comment]
@IdrissSinapan974 Sure....!

how to solve this error
![Untitled](https://user-images.githubusercontent.com/66794033/207825542-0061f51a-dda3-4272-ae93-73c2ce71495f.jpg)

**Comment by kadirnar** [comment]
@pythoncodeAshisH 
Can you share your model? I will update the yolov7-pip package this week. I'll add it to the SAHI algorithm.

Can you try to load your custom model using Yolov7_hubconf?
https://github.com/WongKinYiu/yolov7/blob/main/hubconf.py

This bug is related to the yolov7 repo. To fix this, we can open a Pull Request.

**Comment by beratersari** [comment]
@pythoncodeAshisH Hey, I am also getting error from the predictor which is on the beginning of the notebook. Use the prediction function which is at the end of the notebook. I shared a screenshot below. Use that

![image](https://user-images.githubusercontent.com/56562278/207835022-b5d4ae53-14dc-4303-bb9c-353d535183cc.png)

**Comment by IdrissSinapan974** [comment]
@pythoncodeAshisH  Try to do like @beratersari suggested it should work. There is different way to use SAHI (for only one picture, or a folder containing a lot of pictures). 
If you absolutely need the structure like you are trying to use I will try to post a screenshot of this case of use.

**Comment by pythoncodeAshisH** [comment]
I am trying to use the instant segment model yolov7-seg.pt in sahi

**Comment by kadirnar** [comment]
@pythoncodeAshisH 
You should write the instance segmentation results in the bool_mask variable.
https://github.com/kadirnar/Yolov7-SAHI/blob/main/sahi/model.py#L1154

**Comment by kadirnar** [comment]
Updated SAHI version and added yolov7 pip support.

Yolov7Pip(Class):  https://github.com/kadirnar/Yolov7-SAHI/blob/main/sahi/models/yolov7pip.py
Yolov7Hub(Class): https://github.com/kadirnar/Yolov7-SAHI/blob/main/sahi/models/yolov7hub.py

Demo_Code: Yolov7_Demo: https://github.com/kadirnar/Yolov7-SAHI/blob/main/demo/yolov7_demo.py
Result:
![prediction_visual](https://user-images.githubusercontent.com/36204372/208121345-120d991a-e9ee-4729-b10c-fa71fc5ac8c3.png)

**Comment by msdiki** [comment]
Hi, getting the same error using the older version of this repo. When I use updated version with yolov7hub or yolov7pip, it automatically downloads a traced.pt and does not load my custom model. Earlier, it was working fine. Not sure what to try next.

result = get_sliced_prediction(
  File "/home/sdki/.conda/envs/SAHI/lib/python3.10/site-packages/sahi-0.10.7-py3.10.egg/sahi/predict.py", line 239, in get_sliced_prediction
  File "/home/sdki/.conda/envs/SAHI/lib/python3.10/site-packages/sahi-0.10.7-py3.10.egg/sahi/predict.py", line 91, in get_prediction
  File "/home/sdki/.conda/envs/SAHI/lib/python3.10/site-packages/sahi-0.10.7-py3.10.egg/sahi/model.py", line 1114, in perform_inference
ValueError: Model is not loaded, load it by calling .load_model()

**Comment by danial880** [comment]
I am getting the same error with the new version. It is unable to load a custom model.

**Comment by kadirnar** [comment]
@danial880 , @msdiki 

Can you share the sahi and yolov7 versions?

**Comment by danial880** [comment]
sahi: 0.11.6
yolov7detect: 0.3.1
@kadirnar, please let me know if you need something else

**Comment by kadirnar** [comment]
Where are you running the demo.py file? You have to run it in the yolov7-sahi/ directory. It may throw an error in the demo folder.

> sahi: 0.11.6 yolov7detect: 0.3.1 @kadirnar, please let me know if you need something else

**Comment by danial880** [comment]
I am not using it inside sahi/directory. I have installed your repo using "python setup.py install", and used it in a script.

**Comment by kadirnar** [comment]
Orijinal Repo: https://github.com/obss/sahi
I just added yolov7 and tensorflowhub model support. To use this repo, you must:
```
git clone https://github.com/kadirnar/Yolov7-SAHI
cd Yolov7-SAHI
```
Open a new python file and run the following codes:

Yolov7: https://github.com/kadirnar/Yolov7-SAHI/blob/main/demo/yolov7_demo.py
TensorFlowHub: https://github.com/kadirnar/Yolov7-SAHI/blob/main/demo/tensorflowhub_demo.py

You have to run these files in the yolov7-sahi folder.

**Comment by CesareDavidePace** [comment]
how resolve this problem?

**Comment by kadirnar** [comment]
How did you install? What is the error message? @CesareDavidePace

**Comment by CesareDavidePace** [comment]
I just clone the repository.
And this is the error 
![Cattura](https://user-images.githubusercontent.com/104144011/210669793-98b63c04-cf39-4ab0-9c1f-bd10743ef0fe.PNG)

**Comment by kadirnar** [comment]
Did you run the example yolov7-demo.py file inside the Yolov7-SAHİ folder?

**Comment by danial880** [comment]
I was facing a similar problem. In my scenario, I had to use yolov7-sahi in my project. Therefore I cannot use yolov7-demo.py from inside the yolov7-sahi folder. But the previous version of this repository works fine with custom models and runs from outside the yolov7-sahi folder after installation. [Old Version](https://github.com/danial880/Sahi-Yolov7)

**Comment by kadirnar** [comment]
@danial880  @CesareDavidePace ,
The yolov7_hub module is running slow. You have to use the pip version. Can you download the repo and run the yolo7_demo.py file? I tested it now and it works.

```
git clone https://github.com/kadirnar/Yolov7-SAHI
cd Yolov7-SAHI
```
### Env:
yolov7detect==0.3.1

### Run
```
python yolov7_demo.py
```
### Result:
![prediction_visual](https://user-images.githubusercontent.com/36204372/210726701-fd7585f1-4556-49e4-8ac6-ef7c3ae758af.png)

**Comment by kadirnar** [comment]
This week I will add the SAHI algorithm to this library. You will use it more easily.
https://github.com/kadirnar/torchyolo/issues/9

**Comment by CesareDavidePace** [comment]
![Cattura2](https://user-images.githubusercontent.com/104144011/210732324-3532c755-e788-4883-9e51-32e1b6218a23.PNG)

**Comment by kadirnar** [comment]
> ![Cattura2](https://user-images.githubusercontent.com/104144011/210732324-3532c755-e788-4883-9e51-32e1b6218a23.PNG)

```pip uninstall sahi```

**Comment by CesareDavidePace** [comment]
![Cattura3](https://user-images.githubusercontent.com/104144011/210733474-90c052f7-4343-4f9a-aedc-33c81f21c344.PNG)

**Comment by kadirnar** [comment]
https://github.com/kadirnar/Yolov7-SAHI/blob/main/yolov7_demo.py

You should use this code.

**Comment by CesareDavidePace** [comment]
![Cattura4](https://user-images.githubusercontent.com/104144011/210734417-c6d2fd62-63b0-48f3-9d95-c9ea7d1dc291.PNG)

**Comment by kadirnar** [comment]
Did the yolov7.pt file download while running this file?  Can you print for the self.model_path variable on line 20 of the Yolov7pip.py file?

**Comment by CesareDavidePace** [comment]
Yes, the file has been downloaded.
After install yolov7detect the script work.

But in my file i have the same problem

**Comment by CesareDavidePace** [comment]
Okay I restarted the kernel and everything works fine now. Thanks for your huge help!

**Comment by kadirnar** [comment]
This is great.  This week I will release the pip package for the yolov7-sahi repository.  Good luck.
